### ISSUE TITLE
Rename run_command=>run_python_command

### ISSUE THREAD

**Issue by MaximilienNaveau** [machines-in-motion/dynamic_graph_manager#8]
## Problem

The service names are a bit unclear on what they do.

## Potential Solution

Rename `run_command` => `run_python_command`

**Comment by gazarahmad** [comment]
before doing such a disruptive change it may be important to discuss with everyone affected. the additional cost in terms of all the code that will be broken through this change may not be worth the (alleged) benefit in terms of clarity.
@MaximilienNaveau i strongly suggest to discuss this in a meeting before going ahead with this.
